# Site settings
title: "Kardigan: integrasjon og utvikling"
email: "hei@kardigan.no"
description: "Kardigan er eksperter på integrasjon og programvareutvikling"
lang: no
author: "contact@alexchopin.com"
baseurl: "/kardigan/" # Need to be erase after DNS has been set
url: "" # the base hostname & protocol for your site
google_analytics:

include: ['_pages']

# Build settings
markdown: kramdown
sass:
    style: compressed
